
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ..:/app
    networks:
    - db_net
  db:
    image: postgres:13.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - db_net
    volumes:
      - db_vol:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db_net
networks:
  db_net:
    driver: bridge
volumes:
  db_vol:
    name: db_vol
