
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ..:/app
    networks:
    - db_net_tcc
  db:
    image: postgres:13.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tcc
    networks:
      - db_net_tcc
    volumes:
      - db_vol_tcc:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db_net_tcc
networks:
  db_net_tcc:
    driver: bridge
volumes:
  db_vol_tcc:
    name: db_vol_tcc
